function(add_real_test NAME)
  add_executable(test_${NAME} test_${NAME}.c)
  target_compile_definitions(test_${NAME} PRIVATE "MBEDTLS_ALLOW_PRIVATE_ACCESS")
  target_link_libraries(test_${NAME} PRIVATE ${ARGN} ${CNK_CRYPTO_LIBRARIES})
  if(APPLE OR UNIX)
    target_link_libraries(test_${NAME} PRIVATE dl)
  endif()
  if(RUN_REAL_TESTING)
    add_test(NAME test_${NAME} COMMAND test_${NAME} $<TARGET_FILE:${CNK_PKCS_TARGET}>)
  endif()
endfunction()

add_real_test(real)
add_real_test(pqc)
